python examples/hovering/ppo.py --seed 42 -c std
python examples/landing/ppo.py --seed 42 -c std
python examples/tracking/ppo.py --seed 42 -c std
python examples/racing/ppo.py --seed 42 -c std
python examples/hovering/ppo.py --seed 0 -c std
python examples/landing/ppo.py --seed 0 -c std
python examples/tracking/ppo.py --seed 0 -c std
python examples/racing/ppo.py --seed 0 -c std
python examples/hovering/ppo.py --seed 1 -c std
python examples/landing/ppo.py --seed 1 -c std
python examples/tracking/ppo.py --seed 1 -c std
python examples/racing/ppo.py --seed 1 -c std
python examples/hovering/ppo.py --seed 2 -c std
python examples/landing/ppo.py --seed 2 -c std
python examples/tracking/ppo.py --seed 2 -c std
python examples/racing/ppo.py --seed 2 -c std
python examples/hovering/ppo.py --seed 3 -c std
python examples/landing/ppo.py --seed 3 -c std
python examples/tracking/ppo.py --seed 3 -c std
python examples/racing/ppo.py --seed 3 -c std
